### PR TITLE
Build: Add features for the combined release pipeline

### PR DESCRIPTION
**Pull request by philipwindecker**
IMPORTANT: Remove local workarounds before merging!

#### Add a description
This PR adds a new pipeline that is triggered from the release pipeline in open-simulation-interface.
When triggered, it creates a new tag (identical to the one used for the release) and pushes it.

#### Mention a member
@pmai 

#### Check the checklist

- [x] I have performed a self-review of my own code/documentation.
- [ ] My documentation changes are related to another repository in the organization. Here is the link to the issue/repo.
- [x] My changes generate no new warnings during the documentation generation.
- [ ] The existing travis ci which pushes the documentation to gh-pages passes with my changes.

## Related PRs
- https://github.com/OpenSimulationInterface/osi-antora-generator/pull/3
- https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/92
- https://github.com/OpenSimulationInterface/open-simulation-interface/pull/678

### CODE REVIEW

**Comment by philipwindecker** [comment]
IMPORTANT: Remove local workarounds before merging!

**Comment by philipwindecker** [comment]
@pmai please review soon, otherwise we may get into time conflicts later.
There are still a couple of clean up steps I need to take after your review before we can merge, and likely I will have to do at least one test after merging to make sure everything works on here as it did on my forks.
Thanks!

**Comment by philipwindecker** [comment]
> @pmai please review soon, otherwise we may get into time conflicts later. There are still a couple of clean up steps I need to take after your review before we can merge, and likely I will have to do at least one test after merging to make sure everything works on here as it did on my forks. Thanks!

As dicussed in today's CCB meeting, I removed the workarounds pointing to forked repositories.
Changes can now be merged. Please add review so I can proceed, @pmai .

Note that I will need to confirm operation after merge to make sure all changes work as intended here as well.

**Review by pmai — APPROVED** [review]
Approved as per CCB 2023-03-27.

**Pull request merged**
